import { BatchLineItem } from './types';

export const SAMPLE_TENDER_ITEMS: BatchLineItem[] = [
  {
    id: 'TND-001',
    name: 'Trastuzumab 440mg Lyophilized Vial',
    genericName: 'Trastuzumab',
    dosageForm: 'Injection (Vial)',
    category: 'Cold-Chain Biologics (2°C–8°C)',
    quantity: 500,
    unit: 'Vials',
    quotedUnitPrice: 27900,
    ceilingUnitPrice: 24900,
    dpcoStatus: 'EXCEEDS_CEILING',
    excessPerUnit: 3000,
    totalExcess: 1500000,
    totalQuoted: 13950000,
    statutoryReference: 'DPCO 2013 S.O. 1331(E) NLEM Schedule-I',
  },
  {
    id: 'TND-002',
    name: 'Paclitaxel 260mg/43.4ml Sterile Infusion',
    genericName: 'Paclitaxel',
    dosageForm: 'Injectable Infusion',
    category: 'Oncology Cytotoxics',
    quantity: 1200,
    unit: 'Vials',
    quotedUnitPrice: 3200,
    ceilingUnitPrice: 2988,
    dpcoStatus: 'EXCEEDS_CEILING',
    excessPerUnit: 212,
    totalExcess: 254400,
    totalQuoted: 3840000,
    statutoryReference: 'NPPA Anti-Cancer Price Regulation 2019',
  },
  {
    id: 'TND-003',
    name: 'Amoxicillin + Clavulanic Acid 625mg Tablets',
    genericName: 'Amoxicillin / Clavulanate',
    dosageForm: 'Tablet (Alu-Alu)',
    category: 'Essential Antibiotics',
    quantity: 25000,
    unit: 'Strips (10 tabs)',
    quotedUnitPrice: 145,
    ceilingUnitPrice: 182,
    dpcoStatus: 'WITHIN_CEILING',
    excessPerUnit: 0,
    totalExcess: 0,
    totalQuoted: 3625000,
    statutoryReference: 'DPCO Schedule-II Ceiling Price Order (WPI 2024)',
  },
  {
    id: 'TND-004',
    name: 'Meropenem 1g Sterile Powder for Injection',
    genericName: 'Meropenem',
    dosageForm: 'IV Infusion Vial',
    category: 'Critical Care Injectables',
    quantity: 4000,
    unit: 'Vials',
    quotedUnitPrice: 840,
    ceilingUnitPrice: 950,
    dpcoStatus: 'WITHIN_CEILING',
    excessPerUnit: 0,
    totalExcess: 0,
    totalQuoted: 3360000,
    statutoryReference: 'NPPA Notification S.O. 1245(E)',
  },
  {
    id: 'TND-005',
    name: 'Human Normal Albumin 20% 100ml Infusion',
    genericName: 'Human Albumin',
    dosageForm: 'Infusion Bottle',
    category: 'Blood Products & Biologics',
    quantity: 800,
    unit: 'Bottles',
    quotedUnitPrice: 4450,
    ceilingUnitPrice: 3920,
    dpcoStatus: 'EXCEEDS_CEILING',
    excessPerUnit: 530,
    totalExcess: 424000,
    totalQuoted: 3560000,
    statutoryReference: 'NPPA Order S.O. 1820(E)',
  },
  {
    id: 'TND-006',
    name: 'Insulin Glargine 100 IU/ml 3ml Cartridge',
    genericName: 'Insulin Glargine',
    dosageForm: 'Cartridge (Pen)',
    category: 'Cold-Chain Biologics (2°C–8°C)',
    quantity: 3500,
    unit: 'Cartridges',
    quotedUnitPrice: 540,
    ceilingUnitPrice: 485,
    dpcoStatus: 'EXCEEDS_CEILING',
    excessPerUnit: 55,
    totalExcess: 192500,
    totalQuoted: 1890000,
    statutoryReference: 'DPCO Schedule-I Essential Antidiabetic List',
  },
  {
    id: 'TND-007',
    name: 'Paracetamol 650mg Fast-Action Tablets',
    genericName: 'Paracetamol',
    dosageForm: 'Blister Pack (15 tabs)',
    category: 'Essential Analgesics',
    quantity: 40000,
    unit: 'Strips',
    quotedUnitPrice: 24,
    ceilingUnitPrice: 29.5,
    dpcoStatus: 'WITHIN_CEILING',
    excessPerUnit: 0,
    totalExcess: 0,
    totalQuoted: 960000,
    statutoryReference: 'DPCO 2013 Table-A Regulated Ceiling',
  },
  {
    id: 'TND-008',
    name: 'Enoxaparin Sodium 40mg/0.4ml Syringe',
    genericName: 'Enoxaparin',
    dosageForm: 'Prefilled Syringe',
    category: 'Cardiovascular Anticoagulants',
    quantity: 5000,
    unit: 'PFS Syringes',
    quotedUnitPrice: 410,
    ceilingUnitPrice: 360,
    dpcoStatus: 'EXCEEDS_CEILING',
    excessPerUnit: 50,
    totalExcess: 250000,
    totalQuoted: 2050000,
    statutoryReference: 'NPPA S.O. 2940(E) NLEM 2022 Revised',
  },
  {
    id: 'TND-009',
    name: 'Remdesivir 100mg Lyophilized Powder',
    genericName: 'Remdesivir',
    dosageForm: 'Vial',
    category: 'Specialty Antivirals',
    quantity: 1000,
    unit: 'Vials',
    quotedUnitPrice: 1800,
    ceilingUnitPrice: 2450,
    dpcoStatus: 'WITHIN_CEILING',
    excessPerUnit: 0,
    totalExcess: 0,
    totalQuoted: 1800000,
    statutoryReference: 'Voluntary NPPA Undertaking & NLEM Price Cap',
  },
  {
    id: 'TND-010',
    name: 'Cefoperazone + Sulbactam 1.5g Sterile Vial',
    genericName: 'Cefoperazone / Sulbactam',
    dosageForm: 'Injectable Vial',
    category: 'Essential Antibiotics',
    quantity: 6000,
    unit: 'Vials',
    quotedUnitPrice: 290,
    ceilingUnitPrice: 330,
    dpcoStatus: 'WITHIN_CEILING',
    excessPerUnit: 0,
    totalExcess: 0,
    totalQuoted: 1740000,
    statutoryReference: 'DPCO 2013 Ceiling Price Regulation',
  },
];

export const REFERENCE_DPCO_CEILINGS: Record<string, { ceiling: number; reference: string }> = {
  trastuzumab: { ceiling: 24900, reference: 'DPCO 2013 S.O. 1331(E) NLEM Schedule-I' },
  paclitaxel: { ceiling: 2988, reference: 'NPPA Anti-Cancer Price Regulation 2019' },
  amoxicillin: { ceiling: 182, reference: 'DPCO Schedule-II Ceiling Price Order (WPI 2024)' },
  meropenem: { ceiling: 950, reference: 'NPPA Notification S.O. 1245(E)' },
  albumin: { ceiling: 3920, reference: 'NPPA Order S.O. 1820(E)' },
  insulin: { ceiling: 485, reference: 'DPCO Schedule-I Essential Antidiabetic List' },
  paracetamol: { ceiling: 29.5, reference: 'DPCO 2013 Table-A Regulated Ceiling' },
  enoxaparin: { ceiling: 360, reference: 'NPPA S.O. 2940(E) NLEM 2022 Revised' },
  remdesivir: { ceiling: 2450, reference: 'Voluntary NPPA Undertaking & NLEM Price Cap' },
  cefoperazone: { ceiling: 330, reference: 'DPCO 2013 Ceiling Price Regulation' },
  metformin: { ceiling: 18.5, reference: 'DPCO Table-A Oral Antidiabetic' },
  azithromycin: { ceiling: 112, reference: 'NLEM Antibiotic Ceiling Schedule-I' },
  ciprofloxacin: { ceiling: 42, reference: 'DPCO Standard Oral Anti-Infective' },
};
